
name: Generate Snake Animation

on:
  schedule:
    - cron: "0 */12 * * *" # Executa a cada 12 horas
  workflow_dispatch:

jobs:
  build:
    name: Generate Snake animation
    runs-on: ubuntu-latest

    steps:
      # Checkout do repositório
      - name: Checkout do código
        uses: actions/checkout@v2

      # Geração da animação da cobra
      - name: Gerar a cobra de contribuições
        uses: Platane/snk@v2
        with:
          github_user_name: Rafa-s-s
          output: dist/github-contribution-grid-snake.svg

      # Publicação da cobra no GitHub Pages
      - name: Publicar no GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
